server:
  port: 8002        # 修改访问端口
mybatis:
  type-aliases-package: com.trd.springcloud.entities
  mapper-locations:
    - classpath:mybatis/mapper/*.xml
  configuration:
    cache-enabled: true
spring:
  application:
    name: microservicecloud-dept                    # 不要修改，和8001的保持一致
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/clouddb02    # 修改数据库，验证轮回算法
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: microservicecloud-dept:8002   # 修改注册进eureka server的实例id
    prefer-ip-address: true
info:
  app.name: microservice-SpringCloud
  company.name: www.trd.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$